### ISSUE TITLE
Can multiple threads write to the superrollingfilealternate file?

### ISSUE THREAD

**Issue by kkarakk** [aarondh/SuperRollingFileAlternate#2]
Currently facing an issue where multiple threads can't write to a single log file(which makes serilog file logging useless in production for me)

**Comment by nblumhardt** [comment]
Hey @kkarakk - I think there's some confusion here; Serilog's file sink always supports multiple threads. If you use the `shared: true`, any process can also write to the file. The only issue is if another process tries to open the file with the _exclusive_ option - in which case this will fail.

The only alternative is for the logger to open and close the file on every logging call, which can work around some cases of other processes temporarily opening the file, but performance of this (because of the underlying OS calls that need to be made) is awful, and logging libraries that implement it invariably recommend against using it.

Perhaps there's another approach to achieve what you're aiming to do? Cheers!

**Comment by kkarakk** [comment]
i guess there is some mismatch in my understanding of how serilog should be configured in .net core and how i've done it because shared:true does not work for me. i'm also using a very esoteric usecase of .net core(hosting website in a windows service whilst collecting IoT data using a tcp server implemented in that same service) so it may be failing because of that as well- service might take an exclusive lock when using serilog. Logging normally using a c# file writer works fine(but obv is not as clean or comprehensive)    

luckily .net core is getting support for windows service natively in .net core preview 3(it's kinda a hack in lower versions) so am rewriting focused on that, maybe serilog file sink logging will work better for me there.

**Comment by nblumhardt** [comment]
Thanks for the reply; if you end up narrowing down where the problem might be, let me know - happy to help dig around. The https://gitter.im/serilog/serilog channel is a good place for quick Q&A/debugging, most of the time :-)
